version = 1
SPDX-PackageName = "{{crate_name}}"
SPDX-PackageSupplier = "RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-PackageDownloadLocation = "https://github.com/{{github_username}}/{{crate_name}}"

[[annotations]]
path = ["README.md", ".gitignore", ".rustfmt.toml", "Cargo.lock", "Cargo.toml", "tests/**/*.stderr"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 RAprogramm <andrey.rozanov.vl@gmail.com>"
SPDX-License-Identifier = "MIT"
