version = 1
SPDX-PackageName = "{{project-name}}"
SPDX-PackageSupplier = "{{author_name}} <{{author_email}}>"
SPDX-PackageDownloadLocation = "https://github.com/{{gh_username}}/{{project-name}}"

[[annotations]]
path = [
    "README.md",
    ".gitignore",
    ".rustfmt.toml",
    "Cargo.lock",
    "Cargo.toml",
    ".config/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 {{author_name}} <{{author_email}}>"
SPDX-License-Identifier = "MIT"
